// This file is generated by ‘bs/helpers/languages.js’! Use NAME key in JSON files.

export const languages = {
	cs: "Čeština",
	en: "English",
} as const;

export type Language = keyof typeof languages;
