// generated by bs/dev/assets.js
import type { SvgIconId } from "@/components";
import _svgIconActivitiesId from "./icon-activities.svg";
export const svgIconActivitiesId = _svgIconActivitiesId as SvgIconId;
import _svgIconArrowRightId from "./icon-arrow-right.svg";
export const svgIconArrowRightId = _svgIconArrowRightId as SvgIconId;
import _svgIconMusicOffId from "./icon-music-off.svg";
export const svgIconMusicOffId = _svgIconMusicOffId as SvgIconId;
import _svgIconMusicOnId from "./icon-music-on.svg";
export const svgIconMusicOnId = _svgIconMusicOnId as SvgIconId;
import _svgIconTimerId from "./icon-timer.svg";
export const svgIconTimerId = _svgIconTimerId as SvgIconId;