// generated by bs/dev/assets.js
import type { SvgIconId } from "@/components";
import _svgIconArrowDownUrl from "./icon-arrow-down.svg?no-inline";
export const svgIconArrowDownUrl = _svgIconArrowDownUrl as string;
import _svgIconQrId from "./icon-qr.svg";
export const svgIconQrId = _svgIconQrId as SvgIconId;