#!/usr/bin/env bash

function changed {
	git diff --name-only 'HEAD@{1}' HEAD | grep "^$1" >/dev/null 2>&1
}

if changed 'package-lock.json'; then
	echo '📦 package-lock.json changed.'
	echo 'Run `npm ci` to bring your dependencies up to date.'
	npm ci
fi
exit 0
