// generated by bs/dev/assets.js
import _imageBgUrl from "./bg.png?no-inline";
export const imageBgUrl = _imageBgUrl as string;
import _imageCisLogoUrl from "./cis-logo.png?no-inline";
export const imageCisLogoUrl = _imageCisLogoUrl as string;