#!/usr/bin/env nodejsscript
import { join, relative } from "node:path";
import { describeFromReadme } from "../.common.js";

if ($.isMain(import.meta))
	$.api("", true)
		.describe(describeFromReadme())
		.option("--dry-run", "dry run")
		.option("-a, --all", "prints all assets exports (for dev purposes)")
		.action(async function main({ "dry-run": dryRun, all }) {
			genereateAssetsIndices({ dryRun, all });
			$.exit(0);
		})
		.parse();

/** @param {{ dryRun?: boolean }} [params={}] */
export function genereateAssetsIndices({ dryRun, all } = {}) {
	const paths = s.find("src/**/assets").filter((path) => !path.endsWith(".ts") && !path.includes("fonts"));
	const used = all
		? false
		: pipe(
				Array.from,
				(matches) => matches.flatMap(([_, match]) => match.split(/,\s*/)),
				(items) => new Set(items),
			)(s.grep(/from ".*assets.*"/, "src/**/*.ts*").matchAll(/\{\s*(.*?)\s*\}/gm));
	const todo = [[paths[0], []]];
	for (const path of paths.slice(1)) {
		const [folder, assets] = todo.at(-1);
		if (path.startsWith(folder)) {
			assets.push(path);
			continue;
		}
		todo.push([path, []]);
	}
	for (const [folder, assets] of todo) {
		const content = generateAssetsIndex(folder, assets, used);
		const target = join(folder, "index.ts");
		if (dryRun) echo(`${target}:\n${content}`);
		else s.echo(content).to(target);
	}
}
function generateAssetsIndex(folder, files, used) {
	const out = [];
	let svgType = "";
	for (const fileFull of files) {
		const file = relative(folder, fileFull);
		const type = file.slice(file.lastIndexOf(".") + 1);
		switch (type) {
			case "svg": {
				if (!svgType) svgType = 'import type { SvgIconId } from "@/components";';
				const name = type + PascalCase(file.slice(0, file.lastIndexOf(".")));
				add(name, file, "Id");
				add(name, file, "Url");
				break;
			}
			case "png": {
				const name = `image${PascalCase(file.slice(0, file.lastIndexOf(".")))}`;
				add(name, file, "Url");
				break;
			}
		}
	}
	if (svgType) out.unshift(svgType);
	out.unshift("// generated by bs/dev/assets.js");
	return out.join("\n");

	function add(nameBase, file, type) {
		const name = nameBase + type;
		if (used && !used.has(name)) return;
		const path = `./${file}${type === "Url" ? "?no-inline" : ""}`;
		out.push(
			`import _${name} from "${path}";`,
			`export const ${name} = _${name} as ${type === "Id" ? "SvgIconId" : "string"};`,
		);
	}
}
function camelCase(str) {
	return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}
function PascalCase(str) {
	return str[0].toUpperCase() + camelCase(str.slice(1));
}
