/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/app-__root";
import { Route as IndexRouteImport } from "./app/app-index";
import { Route as DashboardIpRouteImport } from "./app/app-dashboard/app-$ip";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIpRoute = DashboardIpRouteImport.update({
  id: "/dashboard/$ip",
  path: "/dashboard/$ip",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard/$ip": typeof DashboardIpRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard/$ip": typeof DashboardIpRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard/$ip": typeof DashboardIpRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard/$ip";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard/$ip";
  id: "__root__" | "/" | "/dashboard/$ip";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardIpRoute: typeof DashboardIpRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/$ip": {
      id: "/dashboard/$ip";
      path: "/dashboard/$ip";
      fullPath: "/dashboard/$ip";
      preLoaderRoute: typeof DashboardIpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIpRoute: DashboardIpRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
