/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/app-__root";
import { Route as IndexRouteImport } from "./app/app-index";
import { Route as IpIndexRouteImport } from "./app/app-$ip/app-index";
import { Route as IpPresentationIdIndexRouteImport } from "./app/app-$ip/app-$presentationId/app-index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const IpIndexRoute = IpIndexRouteImport.update({
  id: "/$ip/",
  path: "/$ip/",
  getParentRoute: () => rootRouteImport,
} as any);
const IpPresentationIdIndexRoute = IpPresentationIdIndexRouteImport.update({
  id: "/$ip/$presentationId/",
  path: "/$ip/$presentationId/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$ip": typeof IpIndexRoute;
  "/$ip/$presentationId": typeof IpPresentationIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$ip": typeof IpIndexRoute;
  "/$ip/$presentationId": typeof IpPresentationIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$ip/": typeof IpIndexRoute;
  "/$ip/$presentationId/": typeof IpPresentationIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$ip" | "/$ip/$presentationId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$ip" | "/$ip/$presentationId";
  id: "__root__" | "/" | "/$ip/" | "/$ip/$presentationId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  IpIndexRoute: typeof IpIndexRoute;
  IpPresentationIdIndexRoute: typeof IpPresentationIdIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$ip/": {
      id: "/$ip/";
      path: "/$ip";
      fullPath: "/$ip";
      preLoaderRoute: typeof IpIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$ip/$presentationId/": {
      id: "/$ip/$presentationId/";
      path: "/$ip/$presentationId";
      fullPath: "/$ip/$presentationId";
      preLoaderRoute: typeof IpPresentationIdIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IpIndexRoute: IpIndexRoute,
  IpPresentationIdIndexRoute: IpPresentationIdIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
